name: Detect core-python-sdk-pr-py310 Failure

on:
  check_run:
    types: [completed]
  workflow_dispatch:

jobs:
  detect-core-py310-failure:
    name: Detect core-python-sdk-pr-py310 Failure
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: read
    steps:
      - name: Detect failing core-python-sdk-pr-py310 build
        id: detect_failure
        uses: actions/github-script@v6
        with:
          script: |
            try {
              // Use the check_run event payload directly
              const check = context.payload.check_run;
              console.log('Received check_run event.');
              console.log('Check run object:', JSON.stringify(check, null, 2));

              // Detect check runs whose name starts with 'core-python-sdk-pr-py310'
              const isTargetCheck = check && check.name && check.name.startsWith('core-python-sdk-pr-py310');
              if (!isTargetCheck) {
                console.log(`This check run is not for core-python-sdk-pr-py310. Skipping. Name: '${check && check.name}'`);
                core.setOutput('failure_detected', 'false');
                return;
              }

              if (check.status === 'completed' && check.conclusion === 'failure') {
                console.log(`Check '${check.name}' has failed.`);
                core.setOutput('failure_detected', 'true');
                core.setOutput('name', check.name || 'Unknown');
                core.setOutput('id', check.id || '');
                core.setOutput('html_url', check.html_url || '');
                core.setOutput('details_url', check.details_url || '');
                core.setOutput('external_id', check.external_id || '');
              } else {
                console.log(`Check '${check.name}' has not failed.`);
                core.setOutput('failure_detected', 'false');
              }
            } catch (error) {
              console.error(`Unhandled error: ${error.message}`);
              core.setOutput('failure_detected', 'false');
              core.setFailed(`Failed to detect core-python-sdk-pr-py310 failure: ${error.message}`);
            }

      - name: Print detected failure details
        if: steps.detect_failure.outputs.failure_detected == 'true'
        run: |
          echo "core-python-sdk-pr-py310 build failed!"
          echo "Name: ${{ steps.detect_failure.outputs.name }}"
          echo "ID: ${{ steps.detect_failure.outputs.id }}"
          echo "HTML URL: ${{ steps.detect_failure.outputs.html_url }}"
          echo "Details URL: ${{ steps.detect_failure.outputs.details_url }}"
          echo "External ID: ${{ steps.detect_failure.outputs.external_id }}"
